"""Settings Model Extension

Revision ID: 1040470e95e4
Revises: 4b5c6d7e8f9a
Create Date: 2026-04-14 02:18:59.702813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1040470e95e4'
down_revision: Union[str, None] = '4b5c6d7e8f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('website', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('support_email', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('smtp_host', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('smtp_port', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('smtp_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'smtp_password')
    op.drop_column('companies', 'smtp_port')
    op.drop_column('companies', 'smtp_host')
    op.drop_column('companies', 'support_email')
    op.drop_column('companies', 'website')
    # ### end Alembic commands ###
