"""add_gemini_key_to_company

Revision ID: ab85f1225a5b
Revises: 44b4a1a8b7a6
Create Date: 2026-04-14 16:40:19.429122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab85f1225a5b'
down_revision: Union[str, None] = '44b4a1a8b7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('gemini_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'gemini_api_key')
    # ### end Alembic commands ###
